version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      development-dependencies:
        dependency-type: "development"
      scraper:
        patterns:
          - "israeli-bank-scrapers"
      storage-apis:
        patterns:
          - "@actual-app/api"
          - "ynab"
          - "buxfer-ts-client"
      google:
        patterns:
          - "google*"
      database:
        patterns:
          - "azure-kusto*"
          - "pg"
          - "pg-format"
          - "@types/pg*"
      telegram:
        patterns:
          - "telegraf"
          - "@telegraf/entity"
      infra:
        patterns:
          - "@mswjs/interceptors"
          - "async"
          - "date-fns"
          - "debug"
          - "dotenv"
          - "glob"
          - "hash-it"
          - "jsonc-parser"
          - "zod"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
